export interface MaterialPage {
  material: string
  grade: string
  form: string
  slug: string
  displayName: string
  properties: Record<string, string>
  commonUses: string[]
  commonThicknesses: string[]
  relatedGrades: string[]
  description: string
}

export const materialPages: MaterialPage[] = [
  {
    material: "aluminum",
    grade: "6061-T6",
    form: "sheet",
    slug: "aluminum/sheet/6061-t6",
    displayName: "6061-T6 Aluminum Sheet Blanks",
    properties: {
      Alloy: "6061",
      Form: "Sheet",
      "Temper/Condition": "T6 (Solution heat treated and artificially aged)",
      Density: "0.098 lb/in\u00B3 (2.70 g/cm\u00B3)",
      "Tensile Strength": "45,000 psi (310 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "95 Brinell",
    },
    commonUses: [
      "CNC machined enclosures and housings",
      "Mounting plates and brackets",
      "Robotics and automation components",
      "Anodized decorative panels",
      "Electronic heat sinks",
      "Jigs and fixtures",
    ],
    commonThicknesses: [
      '0.040"',
      '0.063"',
      '0.080"',
      '0.090"',
      '0.125"',
      '0.190"',
      '0.250"',
    ],
    relatedGrades: ["5052-H32", "7075-T6", "2024-T3"],
    description:
      "6061-T6 aluminum sheet blanks are the single most versatile aluminum product for machining, fabrication, and prototyping. The T6 temper indicates the material has been solution heat treated and artificially aged to achieve its optimal balance of strength, hardness, and dimensional stability. With a tensile strength of 45,000 psi and excellent machinability, 6061-T6 sheet is the go-to material for CNC machined parts, from simple brackets to complex multi-feature housings.\n\nOne of the standout characteristics of 6061-T6 is its exceptional anodizing response. Type II and Type III hard anodizing produce consistent, uniform coatings that accept dyes evenly, making it the preferred substrate for consumer electronics enclosures, instrument panels, and any part where cosmetic appearance matters alongside functional protection.\n\n6061-T6 sheet blanks are also fully weldable using TIG or MIG processes with 4043 or 5356 filler wire, though the heat-affected zone will revert to a softer T0 temper. For welded assemblies that require full strength, post-weld heat treatment can restore the T6 condition. The alloy offers good corrosion resistance in most atmospheric and marine environments, though it is not recommended for continuous saltwater immersion where 5052 would be the better choice.\n\nOur 6061-T6 sheet blanks are sheared from certified domestic mill stock and are available in standard thicknesses from 0.040 inches through 0.250 inches. Custom sizes are available on request with typical lead times of two to three business days.",
  },
  {
    material: "aluminum",
    grade: "5052-H32",
    form: "sheet",
    slug: "aluminum/sheet/5052-h32",
    displayName: "5052-H32 Aluminum Sheet Blanks",
    properties: {
      Alloy: "5052",
      Form: "Sheet",
      "Temper/Condition": "H32 (Strain-hardened and stabilized)",
      Density: "0.097 lb/in\u00B3 (2.68 g/cm\u00B3)",
      "Tensile Strength": "33,000 psi (228 MPa)",
      "Yield Strength": "28,000 psi (193 MPa)",
      Hardness: "60 Brinell",
    },
    commonUses: [
      "Marine boat hulls and components",
      "Fuel tanks and pressure vessels",
      "Chemical processing equipment",
      "Formed enclosures and covers",
      "Signage and architectural panels",
    ],
    commonThicknesses: [
      '0.032"',
      '0.040"',
      '0.063"',
      '0.080"',
      '0.090"',
      '0.125"',
      '0.190"',
    ],
    relatedGrades: ["6061-T6", "3003-H14", "5083-H321"],
    description:
      "5052-H32 aluminum sheet blanks are the premier choice for applications requiring excellent corrosion resistance combined with good formability. The 5052 alloy derives its properties from a 2.5% magnesium addition that provides strength without heat treatment, while the H32 temper indicates the material has been strain-hardened and stabilized to a quarter-hard condition. This temper strikes an optimal balance between strength and the ability to be bent, formed, and drawn without cracking.\n\nSaltwater corrosion resistance is where 5052 truly distinguishes itself from other aluminum alloys. Unlike 6061, which can suffer from intergranular corrosion in sustained marine exposure, 5052 maintains its structural integrity in continuous contact with seawater, making it the industry standard for boat hulls, marine hardware, and dock components. This same resistance extends to chemical environments, where 5052 outperforms most aluminum alloys against alkalis, salt solutions, and many acids.\n\nThe formability of 5052-H32 sheet makes it ideal for parts that require bending, stamping, or deep drawing. It achieves tighter bend radii than 6061-T6 without cracking, which is critical for enclosures, formed brackets, and tank fabrication. The alloy also welds excellently with 5356 filler wire, producing joints with strength and corrosion resistance close to the base metal.\n\n5052-H32 is not recommended for machining-intensive parts because it tends to produce gummy chips compared to 6061. For applications that combine forming and moderate machining, 5052 remains an excellent option. Our sheet blanks are available in thicknesses from 0.032 inches through 0.190 inches, cut from certified mill stock.",
  },
  {
    material: "steel",
    grade: "A36",
    form: "plate",
    slug: "steel/plate/a36",
    displayName: "A36 Steel Plate Blanks",
    properties: {
      Alloy: "A36 (ASTM A36)",
      Form: "Plate",
      "Temper/Condition": "Hot Rolled",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "58,000-80,000 psi (400-550 MPa)",
      "Yield Strength": "36,000 psi (250 MPa)",
      Hardness: "119-159 Brinell",
    },
    commonUses: [
      "Structural base plates and gussets",
      "Welded frames and supports",
      "Machine bases and mounting plates",
      "General fabrication and repair",
      "Trailer and equipment decking",
    ],
    commonThicknesses: [
      '0.250" (1/4)',
      '0.375" (3/8)',
      '0.500" (1/2)',
      '0.750" (3/4)',
      '1.000" (1)',
      '1.500" (1-1/2)',
      '2.000" (2)',
    ],
    relatedGrades: ["1018", "1045", "4140"],
    description:
      "A36 steel plate blanks are the most widely used structural steel in North America, specified everywhere from skyscraper columns to farm equipment repairs. The A36 designation is an ASTM specification that guarantees a minimum yield strength of 36,000 psi with excellent weldability and ductility, making it the default material for welded structural fabrication. Unlike specific alloy grades, A36 is defined by its mechanical properties rather than exact chemical composition, which gives mills flexibility to optimize production while ensuring consistent performance.\n\nA36 plate is hot rolled, which means it has a characteristic dark mill scale surface and wider dimensional tolerances compared to cold-finished products. For applications where surface finish matters, the mill scale can be removed by grinding, sandblasting, or pickling. The rough surface actually provides an excellent key for paint adhesion, which is why A36 is the preferred substrate for painted structural steel.\n\nWeldability is one of A36's greatest strengths. Its carbon content stays below 0.29%, placing it firmly in the easily weldable range for all common processes. MIG, TIG, stick, and flux-core welding all produce sound joints without preheat requirements for material under one inch thick. This makes A36 plate blanks the go-to starting material for welded brackets, frames, machine bases, and fabricated assemblies.\n\nA36 plate blanks are not the ideal choice for machining-intensive parts, as the hot-rolled surface and variable microstructure can produce inconsistent finishes. For CNC work, 1018 cold-rolled offers better machinability and tighter tolerances. Our A36 plate blanks are flame-cut or saw-cut from certified mill plate in thicknesses from 1/4 inch through 2 inches.",
  },
  {
    material: "steel",
    grade: "1084",
    form: "bar",
    slug: "steel/bar/1084",
    displayName: "1084 High Carbon Steel Bar Blanks",
    properties: {
      Alloy: "AISI 1084",
      Form: "Bar",
      "Temper/Condition": "Annealed",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "119,000 psi (820 MPa) as-rolled",
      "Yield Strength": "66,000 psi (455 MPa) as-rolled",
      Hardness: "60-62 HRC (heat treated)",
    },
    commonUses: [
      "Custom knife blades",
      "Swords and historical reproductions",
      "Chisels and hand tools",
      "Springs and spring steel components",
      "Woodworking tool blades",
      "Axes and hatchets",
    ],
    commonThicknesses: [
      '1/8" x 1-1/2" bar',
      '3/16" x 1-1/2" bar',
      '1/4" x 1-1/2" bar',
      '1/4" x 2" bar',
      '3/8" x 2" bar',
      '1/2" x 2" bar',
    ],
    relatedGrades: ["1095", "O1", "80CrV2", "W2"],
    description:
      "1084 high carbon steel bar blanks are the most popular steel for knife making in North America, prized for their forgiving heat treatment, excellent edge retention, and consistent performance batch to batch. With a carbon content of 0.80-0.93% and a simple manganese alloy system, 1084 achieves working hardness of 60-62 HRC through a straightforward quench-and-temper process that does not require specialized equipment or soak times critical to the minute.\n\nThe heat treatment for 1084 is remarkably simple compared to more complex alloy steels. The steel is heated to 1,475\u00B0F until non-magnetic plus approximately 50\u00B0F, then quenched in fast-moving parks 50 or similar medium-speed oil. After quenching, two temper cycles at 375-400\u00B0F for one hour each produce a blade with 60-61 HRC hardness, excellent toughness, and fine grain structure. This simplicity makes 1084 the steel that knife-making instructors consistently recommend to beginners.\n\nDespite its beginner-friendly reputation, 1084 produces professional-quality knives. The high manganese content promotes deep hardening and fine pearlite formation, which translates to blades that sharpen easily and hold a working edge through heavy use. The steel also etches beautifully for hamon and damascus patterns. Many professional bladesmiths use 1084 as the high-carbon layer in pattern-welded damascus paired with 15N20 nickel steel.\n\n1084 bar stock machines well in the annealed condition and grinds cleanly on belt grinders with standard ceramic or aluminum oxide belts. Our bar blanks are precision-cut from annealed mill stock in the most popular knife-making dimensions, ready for profiling and grinding.",
  },
  {
    material: "steel",
    grade: "D2",
    form: "bar",
    slug: "steel/bar/d2-tool-steel",
    displayName: "D2 Tool Steel Bar Blanks",
    properties: {
      Alloy: "AISI D2",
      Form: "Bar",
      "Temper/Condition": "Annealed",
      Density: "0.278 lb/in\u00B3 (7.70 g/cm\u00B3)",
      "Tensile Strength": "140,000 psi (965 MPa) annealed",
      "Yield Strength": "95,000 psi (655 MPa) annealed",
      Hardness: "58-62 HRC (heat treated)",
    },
    commonUses: [
      "Stamping dies and punches",
      "Industrial cutting blades",
      "Wear plates and guides",
      "High-performance knife blades",
      "Cold-work tooling",
      "Thread rolling dies",
    ],
    commonThicknesses: [
      '1/8" x 2" bar',
      '3/16" x 2" bar',
      '1/4" x 2" bar',
      '3/8" x 2" bar',
      '1/2" x 2" bar',
      '3/4" x 3" bar',
      '1" x 3" bar',
    ],
    relatedGrades: ["O1", "A2", "M2", "CPM 3V"],
    description:
      "D2 tool steel bar blanks are the industry standard for cold-work tooling and high-wear applications where extreme edge retention and abrasion resistance are required. Classified as a high-carbon, high-chromium tool steel, D2 contains approximately 1.5% carbon and 12% chromium. This composition produces a dense matrix of hard chromium carbides that give D2 its legendary wear resistance, roughly seven to ten times that of standard carbon steels.\n\nThe 12% chromium content places D2 in a semi-stainless category. While it does not meet the 13% minimum for true stainless classification, D2 offers significantly better corrosion resistance than carbon steels, O1, or A2 tool steels. It develops a light surface stain rather than deep rust in humid conditions, and with proper care it serves well in moderately corrosive environments.\n\nHeat treating D2 requires more precision than simple carbon steels. The recommended austenitizing temperature is 1,825-1,875\u00B0F with a 20-30 minute soak, followed by air cooling or plate quenching. Triple tempering at 300-400\u00B0F for knife applications or 950\u00B0F for maximum secondary hardness in die applications optimizes the balance between hardness and toughness. D2 achieves 58-62 HRC depending on the tempering temperature selected.\n\nFor knife makers, D2 delivers outstanding edge retention that significantly outperforms 1084 and O1 in slicing tasks, though it requires more effort to sharpen. For tooling applications, D2 bar blanks serve as the starting material for stamping dies, punches, forming tools, and industrial cutting blades where tool life directly impacts production economics. Our D2 bar blanks ship in the annealed condition for easiest machining and profiling.",
  },
  {
    material: "steel",
    grade: "1018",
    form: "bar",
    slug: "steel/bar/1018",
    displayName: "1018 Cold Rolled Steel Bar Blanks",
    properties: {
      Alloy: "AISI 1018",
      Form: "Bar",
      "Temper/Condition": "Cold Rolled",
      Density: "0.284 lb/in\u00B3 (7.87 g/cm\u00B3)",
      "Tensile Strength": "63,800 psi (440 MPa)",
      "Yield Strength": "53,700 psi (370 MPa)",
      Hardness: "126 Brinell",
    },
    commonUses: [
      "Pins, shafts, and spacers",
      "Welded fixtures and jigs",
      "Machine components and bushings",
      "Case-hardened wear parts",
      "Student and hobbyist projects",
      "General-purpose machining stock",
    ],
    commonThicknesses: [
      '1/4" round bar',
      '3/8" round bar',
      '1/2" round bar',
      '3/4" round bar',
      '1" round bar',
      '1/4" x 1" flat bar',
      '1/2" x 2" flat bar',
    ],
    relatedGrades: ["A36", "1045", "12L14", "1117"],
    description:
      "1018 cold rolled steel bar blanks are the most widely used low-carbon steel for machining, welding, and general fabrication. The 1018 designation indicates a plain carbon steel with 0.15-0.20% carbon, placing it in the low-carbon or mild steel category. Cold rolling improves the surface finish, dimensional accuracy, and mechanical properties compared to hot-rolled A36, making 1018 the better choice for any application requiring tight tolerances or a clean machined surface.\n\nMachinability is one of 1018's primary advantages. The low carbon content produces free-cutting chips that evacuate cleanly, and the cold-rolled microstructure machines to a smooth finish without the tearing and built-up edge problems that can plague softer hot-rolled steels. While 12L14 free-machining steel offers faster cutting speeds, 1018 is preferred when the finished part will be welded, since 12L14's lead content can cause porosity in welds.\n\n1018 welds exceptionally well with all common processes and requires no preheat for standard section sizes. The low carbon content virtually eliminates the risk of hydrogen cracking and produces ductile welds with minimal hardening in the heat-affected zone. This combination of machinability and weldability makes 1018 bar stock the default material for machine shops producing fixtures, jigs, and fabricated components.\n\nFor applications requiring a hard wear surface on a tough core, 1018 is an excellent candidate for case hardening. Carburizing at 1,700\u00B0F produces a case depth of 0.030-0.060 inches with surface hardness of 58-62 HRC while the core remains soft and impact-resistant. Our 1018 cold rolled bar blanks are available in round and flat bar configurations, cut to length from certified mill stock.",
  },
  {
    material: "stainless-steel",
    grade: "304",
    form: "sheet",
    slug: "stainless-steel/sheet/304",
    displayName: "304 Stainless Steel Sheet Blanks",
    properties: {
      Alloy: "AISI 304 (UNS S30400)",
      Form: "Sheet",
      "Temper/Condition": "Annealed (2B Mill Finish)",
      Density: "0.289 lb/in\u00B3 (8.00 g/cm\u00B3)",
      "Tensile Strength": "73,200 psi (505 MPa)",
      "Yield Strength": "31,200 psi (215 MPa)",
      Hardness: "123 Brinell (70 HRB)",
    },
    commonUses: [
      "Commercial kitchen equipment",
      "Food processing enclosures",
      "Chemical storage tanks",
      "Architectural trim and panels",
      "Pharmaceutical equipment",
      "Water treatment components",
    ],
    commonThicknesses: [
      '0.030" (22 gauge)',
      '0.048" (18 gauge)',
      '0.060" (16 gauge)',
      '0.075" (14 gauge)',
      '0.105" (12 gauge)',
      '0.120" (11 gauge)',
      '0.187" (3/16)',
    ],
    relatedGrades: ["316", "303", "301", "321"],
    description:
      "304 stainless steel sheet blanks are the world's most widely used stainless steel grade, accounting for roughly half of all stainless steel produced globally. The 18% chromium and 8% nickel composition creates a stable austenitic structure that resists corrosion in a wide range of atmospheric, chemical, and food-contact environments while maintaining excellent formability and weldability. This combination of properties explains why 304 appears in everything from restaurant kitchen walls to pharmaceutical mixing vessels.\n\nThe austenitic structure of 304 gives it exceptional ductility and formability. With 40% elongation at break, 304 sheet can be bent, drawn, and spun into complex shapes without cracking. This makes it the preferred material for formed enclosures, sinks, countertops, and decorative architectural elements. The material work-hardens significantly during forming, which increases strength in the finished part but requires awareness of spring-back in brake-formed bends.\n\n304 stainless sheet is available in several surface finishes that affect both appearance and performance. The standard 2B mill finish provides a smooth, moderately reflective surface suitable for most applications. No. 4 brushed finish adds a directional grain pattern preferred for architectural and kitchen applications. Mirror-polished No. 8 finish is available for decorative and sanitary applications. Each finish can be passivated after fabrication to maximize corrosion performance.\n\nWelding 304 sheet requires attention to heat input to minimize carbide precipitation and distortion. TIG welding with 308L filler wire is the standard process for sheet gauges, producing clean, corrosion-resistant joints. Our 304 stainless sheet blanks are sheared from certified 2B mill finish coil stock in standard gauges from 22 gauge through 3/16 inch.",
  },
  {
    material: "copper",
    grade: "C110",
    form: "sheet",
    slug: "copper/sheet/c110",
    displayName: "C110 ETP Copper Sheet Blanks",
    properties: {
      Alloy: "C110 (UNS C11000)",
      Form: "Sheet",
      "Temper/Condition": "H02 (Half Hard)",
      Density: "0.323 lb/in\u00B3 (8.94 g/cm\u00B3)",
      "Tensile Strength": "38,000 psi (262 MPa)",
      "Yield Strength": "30,000 psi (207 MPa)",
      Hardness: "65 HRF",
    },
    commonUses: [
      "Custom busbars and electrical conductors",
      "Grounding plates and straps",
      "Heat sinks and thermal spreaders",
      "Roofing and architectural flashing",
      "Gaskets and shims",
    ],
    commonThicknesses: [
      '0.021" (24 gauge)',
      '0.032" (20 gauge)',
      '0.040" (18 gauge)',
      '0.063" (16 gauge)',
      '0.093"',
      '0.125" (1/8)',
      '0.187" (3/16)',
    ],
    relatedGrades: ["C101", "C122", "C145"],
    description:
      "C110 ETP (Electrolytic Tough Pitch) copper sheet blanks are the industry standard for electrical and thermal applications, delivering 101% IACS electrical conductivity and 391 W/m-K thermal conductivity that no other commercially available engineering metal can match. The ETP designation indicates the copper has been electrolytically refined to 99.90% minimum purity with a controlled oxygen content of approximately 0.04% that does not significantly impact conductivity.\n\nElectrical applications represent the largest use case for C110 copper sheet blanks. Custom busbars sheared or machined from sheet stock are the backbone of power distribution in electrical panels, battery systems, and industrial switchgear. The material's high conductivity means smaller cross-sections can carry equivalent current compared to aluminum, which matters in space-constrained enclosures. Copper's superior connection reliability through bolted, soldered, and crimped joints further cements its position as the preferred busbar material.\n\nThermal management is the second major application area. C110 copper sheet is machined into heat spreaders, cold plates, and thermal interface components for power electronics, LED lighting, and laser systems. The thermal conductivity advantage over aluminum (391 vs. 167 W/m-K) justifies copper's weight and cost premium in applications where heat dissipation directly limits system performance.\n\nC110 copper sheet blanks are available in soft (annealed), half-hard, and hard tempers. Soft temper offers maximum formability for gaskets, formed enclosures, and roofing applications. Half-hard and hard tempers provide improved flatness and rigidity for machined busbars and structural electrical components. Our blanks are sheared from certified mill sheet in gauges from 24 gauge through 3/16 inch with protective interleaving to preserve surface quality.",
  },
  {
    material: "brass",
    grade: "C260",
    form: "sheet",
    slug: "brass/sheet/c260",
    displayName: "C260 Cartridge Brass Sheet Blanks",
    properties: {
      Alloy: "C260 (UNS C26000)",
      Form: "Sheet",
      "Temper/Condition": "H02 (Half Hard)",
      Density: "0.308 lb/in\u00B3 (8.53 g/cm\u00B3)",
      "Tensile Strength": "56,000 psi (386 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "120 HV",
    },
    commonUses: [
      "Engraving plates and nameplates",
      "Stamped hardware and decorative fittings",
      "Ammunition cartridge cases",
      "Musical instrument components",
      "Radiator cores and tanks",
      "Jewelry and craft blanks",
    ],
    commonThicknesses: [
      '0.010"',
      '0.020"',
      '0.032"',
      '0.040"',
      '0.063"',
      '0.093"',
      '0.125"',
    ],
    relatedGrades: ["C360", "C230", "C280"],
    description:
      "C260 cartridge brass sheet blanks are the most popular brass alloy for stamping, forming, and decorative fabrication. The 70/30 copper-to-zinc ratio gives C260 an attractive golden color, excellent cold working characteristics, and good corrosion resistance that has made it the default brass sheet material since the 19th century. The name \"cartridge brass\" comes from its original use in ammunition cartridge cases, where deep drawing capability and reliable performance under pressure are essential.\n\nFormability is the defining characteristic of C260 sheet. In the annealed condition, the alloy achieves 65% elongation, allowing it to be deep drawn, stamped, spun, and formed into complex shapes that would crack harder alloys. This makes C260 sheet blanks the starting material for stamped hardware, drawn cups, formed enclosures, and decorative elements. The material work-hardens progressively during forming, which increases strength in the finished part and allows intermediate annealing for multi-stage forming operations.\n\nC260 sheet blanks are widely used for engraving plates, nameplates, and etched signage. The alloy engraves cleanly by rotary, diamond-drag, and laser methods, and the contrasting bright-cut lines against the golden surface produce highly legible markings. Chemical etching with ferric chloride is another common patterning technique used for decorative panels, circuit board-style patterns, and model-making components.\n\nThe alloy is readily soldered with standard tin-lead or lead-free solders and silver brazing alloys, making it suitable for assembled decorative work, jewelry, and plumbing applications. C260 cannot be heat treated to increase hardness; strength is controlled through cold working and temper selection. Our C260 sheet blanks are available in tempers from soft anneal through spring hard, in thicknesses from 0.010 inches through 0.125 inches.",
  },
  {
    material: "aluminum",
    grade: "6061-T6",
    form: "disc",
    slug: "aluminum/disc/6061-t6",
    displayName: "6061-T6 Aluminum Disc Blanks",
    properties: {
      Alloy: "6061",
      Form: "Disc",
      "Temper/Condition": "T6 (Solution heat treated and artificially aged)",
      Density: "0.098 lb/in\u00B3 (2.70 g/cm\u00B3)",
      "Tensile Strength": "45,000 psi (310 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "95 Brinell",
    },
    commonUses: [
      "Lathe-turned parts and prototypes",
      "Circular mounting flanges",
      "Lazy susan bearings and turntable bases",
      "Speaker adapter rings",
      "Custom gauge faces and dial blanks",
      "Disc brake spacers and adapters",
    ],
    commonThicknesses: [
      '1/8" x 3" diameter',
      '1/4" x 3" diameter',
      '1/4" x 4" diameter',
      '3/8" x 4" diameter',
      '1/2" x 4" diameter',
      '1/2" x 6" diameter',
      '3/4" x 6" diameter',
    ],
    relatedGrades: ["7075-T6", "2024-T3", "6061-T651"],
    description:
      "6061-T6 aluminum disc blanks provide precision-cut circular starting stock for lathe turning, CNC machining, and fabrication of round components. Each disc is waterjet or laser cut from certified 6061-T6 plate stock, ensuring the same mechanical properties and alloy consistency as our sheet and plate products. The circular shape eliminates the rough material removal step that wastes time and tooling when machining round parts from square stock, getting you to the finished dimension faster and with less material waste.\n\nLathe work is the primary application for aluminum disc blanks. Hobbyist and professional machinists use them as starting stock for flanges, bushings, adapter plates, pulley blanks, and custom turned components. The disc format mounts directly in a three-jaw or four-jaw chuck without the awkward clamping geometry of rectangular stock, improving concentricity and reducing setup time. For CNC lathes, the consistent diameter ensures reliable automated loading.\n\nDisc blanks are also popular for applications that need a finished circular shape without extensive machining. Speaker adapter rings, gauge face blanks, decorative medallions, and coaster blanks can be produced from disc stock with minimal finishing. The 6061-T6 alloy anodizes consistently for color-matched decorative applications and provides enough strength for structural mounting flanges and adapters.\n\nAll of our 6061-T6 disc blanks are deburred and inspected for dimensional accuracy before shipping. Standard diameters range from 2 inches to 12 inches in thicknesses from 1/8 inch through 1 inch. Tolerances on diameter are plus or minus 0.015 inches for waterjet-cut discs and plus or minus 0.005 inches for laser-cut discs. Custom diameters and thicknesses are available with short lead times.",
  },
  // --- Steel: 4140 Pre-Hardened Bar ---
  {
    material: "steel",
    grade: "4140",
    form: "bar",
    slug: "steel/bar/4140",
    displayName: "4140 Pre-Hardened Alloy Steel Bar Blanks",
    properties: {
      Alloy: "AISI/SAE 4140 (UNS G41400)",
      Form: "Bar",
      "Temper/Condition": "Pre-Hardened (Quenched & Tempered)",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "145,000 psi (1,000 MPa)",
      "Yield Strength": "120,000 psi (827 MPa)",
      Hardness: "28-32 HRC (270-302 Brinell)",
    },
    commonUses: [
      "Hydraulic shafts and cylinders",
      "Gear blanks and power transmission components",
      "Drill collars and tool joints (oil & gas)",
      "Mold bases for plastic injection molding",
      "Axle shafts and crankshafts",
      "High-stress bolting and studs",
    ],
    commonThicknesses: [
      '1" diameter',
      '1.5" diameter',
      '2" diameter',
      '2.5" diameter',
      '3" diameter',
      '4" diameter',
      '5" diameter',
      '6" diameter',
    ],
    relatedGrades: ["4130", "4340", "8620", "4150"],
    description:
      "4140 pre-hardened bar stock is a chromium-molybdenum alloy steel delivered in the quenched and tempered condition at 28-32 HRC, ready for machining directly into high-strength components without additional heat treatment. The alloy's nominal composition of 0.40% carbon, 0.95% chromium, and 0.20% molybdenum provides an exceptional combination of through-hardenability, fatigue resistance, and toughness that has made 4140 the most widely specified alloy bar steel in North American industry.\n\nThe pre-hardened condition eliminates the heat treatment step from the production process, which saves time, reduces distortion risk, and removes the need for in-house heat treating equipment. At 28-32 HRC, the material machines predictably with carbide tooling at moderate speeds, producing a clean surface finish suitable for hydraulic cylinder rods, mold bases, and precision mechanical components.\n\nFatigue strength is a defining advantage of 4140 over plain carbon steels. The chromium and molybdenum additions refine the grain structure during heat treatment, producing superior resistance to cyclic loading. This makes pre-hardened 4140 the standard material for rotating shafts, gears, and other components subjected to repeated stress reversals. The alloy also responds well to nitriding, which can produce a surface hardness exceeding 60 HRC while maintaining the tough 28-32 HRC core.\n\n4140 pre-hardened bar is weldable with precautions. Preheating to 400-600\u00B0F and using low-hydrogen electrodes or ER80S-D2 MIG wire minimizes the risk of hydrogen-induced cracking in the heat-affected zone. Post-weld stress relief at 1,050-1,100\u00B0F is recommended for structural applications.",
  },
  // --- Steel: 1045 Cold Drawn Bar ---
  {
    material: "steel",
    grade: "1045",
    form: "bar",
    slug: "steel/bar/1045",
    displayName: "1045 Cold Drawn Steel Bar Blanks",
    properties: {
      Alloy: "AISI/SAE 1045 (UNS G10450)",
      Form: "Bar",
      "Temper/Condition": "Cold Drawn",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "91,000 psi (627 MPa)",
      "Yield Strength": "77,000 psi (531 MPa)",
      Hardness: "170-210 Brinell",
    },
    commonUses: [
      "Shafts, axles, and spindles",
      "Bolts, studs, and fasteners",
      "Gears and pinions",
      "Machine tool components",
      "Hydraulic cylinder rods",
      "Agricultural equipment parts",
    ],
    commonThicknesses: [
      '1/2" diameter',
      '3/4" diameter',
      '1" diameter',
      '1.25" diameter',
      '1.5" diameter',
      '2" diameter',
      '2.5" diameter',
      '3" diameter',
    ],
    relatedGrades: ["1018", "4140", "1050", "1144"],
    description:
      "1045 cold drawn bar stock is the workhorse medium carbon steel for shafts, pins, gears, and general-purpose machine components that require higher strength than mild steel without the cost of alloy grades. With 0.43-0.50% carbon content, 1045 occupies the practical midpoint of the carbon steel spectrum, delivering significantly improved tensile and yield strength over 1018 while retaining adequate machinability and weldability for most shop operations.\n\nCold drawing improves the mechanical properties of 1045 substantially compared to the hot-rolled condition. The drawing process increases tensile strength to approximately 91,000 psi and yield strength to 77,000 psi while producing a smooth, bright surface finish with dimensional tolerances far tighter than hot-rolled bar. The resulting product machines cleanly with good surface finish quality, making cold drawn 1045 the preferred starting stock for turned shafts, ground rods, and precision pins.\n\nOne of the key advantages of 1045 is its versatility in heat treatment. The 0.45% carbon content provides enough carbon for meaningful hardening, achieving 50-55 HRC through conventional quench and temper. Induction hardening of bearing surfaces and wear areas is particularly effective with 1045, producing a hard case of 55-58 HRC over a tough core.\n\nWelding 1045 requires more care than low-carbon steels due to its higher carbon equivalent. Preheating to 300-500\u00B0F and using low-hydrogen processes prevents cracking in the heat-affected zone. Our bar blanks are saw-cut from certified domestic cold drawn stock in standard diameters from 1/2 inch through 3 inches.",
  },
  // --- Steel: O1 Tool Steel Bar ---
  {
    material: "steel",
    grade: "O1",
    form: "bar",
    slug: "steel/bar/o1",
    displayName: "O1 Tool Steel Bar Blanks",
    properties: {
      Alloy: "AISI O1 (UNS T31501)",
      Form: "Bar",
      "Temper/Condition": "Annealed",
      Density: "0.283 lb/in\u00B3 (7.83 g/cm\u00B3)",
      "Tensile Strength": "102,000 psi (703 MPa) annealed",
      "Yield Strength": "60,000 psi (414 MPa) annealed",
      Hardness: "201 Brinell annealed; 57-62 HRC heat treated",
    },
    commonUses: [
      "Custom knife blades and hand tools",
      "Blanking and forming dies",
      "Gauges, templates, and precision tooling",
      "Taps, reamers, and cutting tools",
      "Punches and cold-work stamps",
      "Woodworking blades and chisels",
    ],
    commonThicknesses: [
      '1/8" x 1" bar',
      '1/8" x 2" bar',
      '3/16" x 1-1/2" bar',
      '1/4" x 2" bar',
      '3/8" x 2" bar',
      '1/2" x 2" bar',
      '3/4" x 2-1/2" bar',
      '1" x 3" bar',
    ],
    relatedGrades: ["A2", "W1", "D2", "1095"],
    description:
      "O1 tool steel bar blanks are the classic oil-hardening tool steel, valued for their predictable heat treatment, excellent dimensional stability during hardening, and fine grain structure that produces keen cutting edges. The nominal composition of 0.90% carbon, 1.0% manganese, 0.50% chromium, and 0.50% tungsten creates a shallow-hardening steel that responds to simple workshop heat treatment while delivering professional-grade tooling performance.\n\nHeat treating O1 is straightforward and well-documented. The steel is austenitized at 1,450-1,500\u00B0F, soaked for 10-30 minutes depending on cross-section, and quenched in warm oil at 120-150\u00B0F. This produces an as-quenched hardness of 63-65 HRC. Tempering at 300-400\u00B0F for knife and cutting tool applications yields a working hardness of 59-61 HRC with good toughness.\n\nThe fine-grained microstructure of O1 is its signature advantage for cutting tools and blades. The tungsten and chromium additions form small, well-distributed carbides that support an extremely fine edge. Knife makers prize O1 for its ability to take and hold a razor edge, and tool and die makers rely on its clean shearing action in blanking dies. The steel also etches beautifully with ferric chloride, producing high-contrast patterns favored by custom knife makers.\n\nO1 offers better wear resistance than W1 water-hardening steel and is easier to grind than D2 or A2 in the hardened condition. The trade-off is lower wear resistance compared to those higher-alloy tool steels and essentially no corrosion resistance. Our O1 bar blanks ship in the annealed condition, precision ground to standard flat bar dimensions.",
  },
  // --- Steel: A2 Tool Steel Bar ---
  {
    material: "steel",
    grade: "A2",
    form: "bar",
    slug: "steel/bar/a2",
    displayName: "A2 Tool Steel Bar Blanks",
    properties: {
      Alloy: "AISI A2 (UNS T30102)",
      Form: "Bar",
      "Temper/Condition": "Annealed",
      Density: "0.284 lb/in\u00B3 (7.86 g/cm\u00B3)",
      "Tensile Strength": "105,000 psi (724 MPa) annealed",
      "Yield Strength": "65,000 psi (448 MPa) annealed",
      Hardness: "207-235 Brinell annealed; 57-62 HRC heat treated",
    },
    commonUses: [
      "Blanking and forming dies",
      "Punches and cold heading tools",
      "Shear blades and slitter knives",
      "Injection mold cavities and cores",
      "Gauges and precision measuring tools",
      "Coining and embossing dies",
    ],
    commonThicknesses: [
      '1/4" x 2" bar',
      '3/8" x 2" bar',
      '1/2" x 2" bar',
      '3/4" x 3" bar',
      '1" x 3" bar',
      '1" x 5" bar',
      '1.5" x 5" bar',
      '2" x 6" bar',
    ],
    relatedGrades: ["O1", "D2", "S7", "A6"],
    description:
      "A2 tool steel bar blanks are the premier air-hardening cold work tool steel, delivering the best overall balance of wear resistance, toughness, and dimensional stability in heat treatment among the common tool steel grades. The nominal composition of 1.00% carbon, 5.25% chromium, 1.10% molybdenum, and 0.25% vanadium produces a deep-hardening steel that achieves full hardness by air cooling rather than oil or water quenching, resulting in minimal distortion and predictable size change.\n\nThe air-hardening characteristic is A2's defining advantage for precision tooling. Because the steel does not require the rapid cooling of an oil or water quench, thermal gradients during hardening are greatly reduced. This translates to less warping, less cracking risk, and more consistent final dimensions compared to O1 or water-hardening grades. For complex die shapes, tight-tolerance gauges, and mold components where post-heat-treatment grinding must be minimized, A2 is the standard specification.\n\nHeat treatment for A2 involves austenitizing at 1,750-1,800\u00B0F with a 20-45 minute soak, followed by air cooling. As-quenched hardness reaches 62-64 HRC. Double tempering at 350-400\u00B0F yields 59-61 HRC for cold work tooling, while tempering at 950\u00B0F takes advantage of A2's secondary hardening peak for applications requiring hot work resistance.\n\nA2 offers better toughness than D2 at comparable hardness, making it the preferred choice for tooling subjected to impact loading such as blanking punches, cold heading dies, and shear blades. Our A2 bar blanks ship in the annealed condition, precision ground to standard flat bar and oversized block dimensions.",
  },
  // --- Steel: 1095 High Carbon Bar ---
  {
    material: "steel",
    grade: "1095",
    form: "bar",
    slug: "steel/bar/1095",
    displayName: "1095 High Carbon Steel Bar Blanks",
    properties: {
      Alloy: "AISI/SAE 1095 (UNS G10950)",
      Form: "Bar",
      "Temper/Condition": "Annealed",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "100,000 psi (690 MPa) annealed",
      "Yield Strength": "55,000 psi (379 MPa) annealed",
      Hardness: "197 Brinell annealed; 58-64 HRC heat treated",
    },
    commonUses: [
      "Spring stock and flat springs",
      "Knife and sword blades",
      "Hand tools (scrapers, chisels)",
      "Agricultural cutting edges",
      "Band saw and hacksaw blades",
      "Wear-resistant shims and spacers",
    ],
    commonThicknesses: [
      '1/16" x 1" bar',
      '1/8" x 1" bar',
      '1/8" x 1-1/2" bar',
      '3/16" x 1-1/2" bar',
      '1/4" x 1-1/2" bar',
      '1/4" x 2" bar',
      '3/8" x 2" bar',
      '1/2" x 2" bar',
    ],
    relatedGrades: ["1084", "1075", "O1", "W2"],
    description:
      "1095 high carbon steel bar blanks are the traditional choice for springs, blades, and wear components that demand maximum hardness from a simple carbon steel. With 0.90-1.03% carbon and minimal alloying elements, 1095 represents the practical upper limit of the AISI 10xx plain carbon series, delivering the highest attainable hardness and wear resistance from an inexpensive, readily available steel.\n\nThe high carbon content of 1095 allows it to reach 63-65 HRC as-quenched, with typical working hardness of 58-62 HRC after tempering depending on the application. For knives and cutting tools, tempering at 375-425\u00B0F produces 59-61 HRC with adequate toughness for light to moderate duty blades. For spring applications, tempering at 750-850\u00B0F reduces hardness to 48-52 HRC while maximizing elastic resilience and fatigue life.\n\nKnife makers should understand that 1095 behaves differently from 1084 during heat treatment. The higher carbon content makes 1095 a shallower hardening steel with a narrower optimal austenitizing window around 1,475\u00B0F. A fast quench in water, brine, or fast oil is required for full hardness, and the risk of quench cracking is higher than with the more forgiving 1084.\n\nIn its annealed condition, 1095 machines and grinds well for profiling blade shapes and machining spring forms. One key consideration is that 1095 has essentially no corrosion resistance, and blades and springs must be protected with oil, coating, or surface treatment to prevent rust. Our 1095 bar blanks are annealed to maximum softness and cut from certified mill stock.",
  },
  // --- Steel: AR400 Plate ---
  {
    material: "steel",
    grade: "AR400",
    form: "plate",
    slug: "steel/plate/ar400",
    displayName: "AR400 Abrasion-Resistant Plate Blanks",
    properties: {
      Alloy: "AR400",
      Form: "Plate",
      "Temper/Condition": "Quenched & Tempered",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "185,000 psi (1,275 MPa)",
      "Yield Strength": "150,000 psi (1,034 MPa) minimum",
      Hardness: "360-440 Brinell (38-47 HRC)",
    },
    commonUses: [
      "Dump truck and trailer bed liners",
      "Excavator and loader bucket wear plates",
      "Chute and hopper liners",
      "Crusher and conveyor wear surfaces",
      "Mining and aggregate equipment",
      "Ballistic and armor plate applications",
    ],
    commonThicknesses: [
      '3/16" (0.1875")',
      '1/4" (0.250")',
      '3/8" (0.375")',
      '1/2" (0.500")',
      '3/4" (0.750")',
      '1" (1.000")',
      '1-1/4" (1.250")',
      '1-1/2" (1.500")',
    ],
    relatedGrades: ["AR450", "AR500", "Hardox 400", "A514"],
    description:
      "AR400 abrasion-resistant plate is a through-hardened, quenched and tempered steel plate engineered to withstand severe sliding abrasion, impact, and gouging in mining, construction, and material-handling environments. The 400 designation refers to the nominal Brinell hardness of 400, which delivers approximately three to four times the service life of standard A36 structural plate in abrasive wear applications.\n\nThe quenched and tempered microstructure of AR400 consists primarily of tempered martensite, which provides the combination of high hardness and sufficient toughness to resist impact and flexural loading encountered in service. Unlike through-hardened tool steels, AR400 is specifically formulated for weldability. The chemistry is controlled to a carbon equivalent of 0.58 maximum, which allows field welding with proper procedures including preheating to 200-400\u00B0F depending on thickness and using low-hydrogen electrodes.\n\nFabricating AR400 requires awareness of its high hardness. Plasma and oxy-fuel cutting both work well, though the heat-affected zone will soften locally to approximately 250-300 Brinell. Drilling should use carbide-tipped bits at slow speeds with heavy feed pressure and flood coolant. Bending is possible at wider radii than mild steel, with a minimum recommended bend radius of 4-5 times the plate thickness for transverse bends.\n\nAR400 is typically specified as a liner material rather than a primary structural member. It is welded or bolted over structural steel frames in dump bodies, hoppers, chutes, and screens where the wear surface can be replaced when consumed. Our AR400 plate blanks are flame-cut or plasma-cut from certified domestic mill plate.",
  },
  // --- Steel: A572 Grade 50 Plate ---
  {
    material: "steel",
    grade: "A572-50",
    form: "plate",
    slug: "steel/plate/a572-50",
    displayName: "A572 Grade 50 Steel Plate Blanks",
    properties: {
      Alloy: "ASTM A572 Grade 50",
      Form: "Plate",
      "Temper/Condition": "Hot Rolled",
      Density: "0.284 lb/in\u00B3 (7.85 g/cm\u00B3)",
      "Tensile Strength": "65,000 psi (450 MPa) minimum",
      "Yield Strength": "50,000 psi (345 MPa) minimum",
      Hardness: "150-180 Brinell",
    },
    commonUses: [
      "Structural columns, beams, and base plates",
      "Bridge and highway infrastructure",
      "Heavy equipment frames and chassis",
      "Crane and boom fabrication",
      "Storage tank and pressure vessel shells",
      "Transmission towers and utility structures",
    ],
    commonThicknesses: [
      '1/4" (0.250")',
      '3/8" (0.375")',
      '1/2" (0.500")',
      '5/8" (0.625")',
      '3/4" (0.750")',
      '1" (1.000")',
      '1-1/4" (1.250")',
      '1-1/2" (1.500")',
    ],
    relatedGrades: ["A36", "A588", "A514", "A516 Gr. 70"],
    description:
      "A572 Grade 50 steel plate is the most widely specified high-strength low-alloy structural steel in North America, offering a 39% improvement in minimum yield strength over A36 at a modest cost premium. The ASTM A572 specification guarantees a minimum yield strength of 50,000 psi and minimum tensile strength of 65,000 psi, enabling structural engineers to design lighter, more efficient structures that reduce total steel tonnage.\n\nThe high-strength low-alloy approach achieves elevated mechanical properties through micro-additions of columbium (niobium), vanadium, or nitrogen rather than increased carbon content. This is a critical distinction from quenched and tempered steels, because the low carbon equivalent of A572 Grade 50 preserves excellent weldability. The material welds with all standard processes using matching E70XX electrodes without mandatory preheat requirements for thicknesses up to approximately 1-1/2 inches.\n\nBuilding codes and design specifications increasingly favor A572 Grade 50 over A36 for structural applications. The AISC Steel Construction Manual lists Grade 50 as the default specification for W-shapes, and most domestic mills now roll structural shapes exclusively to the dual-certified A36/A572 Grade 50 standard. For plate applications, specifying A572 Grade 50 ensures consistent 50 ksi minimum yield regardless of thickness.\n\nA572 Grade 50 plate is hot rolled with the characteristic mill scale surface common to structural steels. It is available with Charpy impact testing to meet seismic and low-temperature requirements when specified. Our A572 Grade 50 plate blanks are flame-cut, plasma-cut, or saw-cut from certified domestic mill plate in thicknesses from 1/4 inch through 1-1/2 inches.",
  },
  // --- Aluminum: 7075-T6 Sheet ---
  {
    material: "aluminum",
    grade: "7075-T6",
    form: "sheet",
    slug: "aluminum/sheet/7075-t6",
    displayName: "7075-T6 Aluminum Sheet Blanks",
    properties: {
      Alloy: "7075 (UNS A97075)",
      Form: "Sheet",
      "Temper/Condition": "T6 (Solution heat treated and artificially aged)",
      Density: "0.101 lb/in\u00B3 (2.81 g/cm\u00B3)",
      "Tensile Strength": "83,000 psi (572 MPa)",
      "Yield Strength": "73,000 psi (503 MPa)",
      Hardness: "150 Brinell",
    },
    commonUses: [
      "Aerospace structural components",
      "High-performance drone frames",
      "Competition firearm receivers",
      "Rock climbing and mountaineering hardware",
      "Bicycle and motorcycle components",
      "Military and defense fittings",
    ],
    commonThicknesses: [
      '0.020"',
      '0.032"',
      '0.040"',
      '0.063"',
      '0.080"',
      '0.090"',
      '0.125"',
      '0.190"',
    ],
    relatedGrades: ["7075-T651", "2024-T3", "6061-T6"],
    description:
      "7075-T6 aluminum sheet blanks deliver the highest strength available in a standard wrought aluminum alloy, with tensile strength of 83,000 psi that rivals many structural steels at roughly one-third the weight. The 7075 alloy is a zinc-based system (5.1-6.1% zinc, 2.1-2.9% magnesium, 1.2-2.0% copper) that achieves its exceptional strength through the T6 precipitation hardening treatment. This makes 7075-T6 sheet the default material for aerospace structures, high-performance sporting goods, and any application where strength-to-weight ratio is the primary design driver.\n\nUnlike 6061-T6, which offers a balance of properties including good weldability and anodizing response, 7075-T6 is optimized purely for mechanical performance. The alloy is not recommended for fusion welding because the heat-affected zone becomes susceptible to stress corrosion cracking. Mechanical fastening, adhesive bonding, and friction stir welding are the preferred joining methods.\n\n7075-T6 sheet machines well with sharp carbide tooling at moderate to high speeds. The higher hardness compared to 6061 actually produces cleaner chip formation and better surface finishes in many operations. The alloy is an excellent candidate for CNC profiling of complex aerospace brackets, gussets, and structural fittings where every gram of weight savings matters.\n\nCorrosion resistance of 7075-T6 is adequate for most atmospheric environments but inferior to 6061 and significantly inferior to 5052. For applications requiring both high strength and enhanced corrosion protection, alclad 7075-T6 sheet is available with a thin layer of commercially pure aluminum metallurgically bonded to each surface. Our 7075-T6 sheet blanks are sheared from certified aerospace-grade mill stock in thicknesses from 0.020 inches through 0.190 inches.",
  },
  // --- Aluminum: 7075-T651 Plate ---
  {
    material: "aluminum",
    grade: "7075-T651",
    form: "plate",
    slug: "aluminum/plate/7075-t6",
    displayName: "7075-T6 Aluminum Plate Blanks",
    properties: {
      Alloy: "7075 (UNS A97075)",
      Form: "Plate",
      "Temper/Condition": "T651 (Solution heat treated, stress relieved, artificially aged)",
      Density: "0.101 lb/in\u00B3 (2.81 g/cm\u00B3)",
      "Tensile Strength": "83,000 psi (572 MPa)",
      "Yield Strength": "73,000 psi (503 MPa)",
      Hardness: "150 Brinell",
    },
    commonUses: [
      "CNC machined aerospace structural parts",
      "Mold and die backing plates",
      "Military armor and ballistic components",
      "High-performance automotive brackets",
      "Satellite and spacecraft structures",
      "Competition robotics chassis plates",
    ],
    commonThicknesses: [
      '0.250" (1/4)',
      '0.375" (3/8)',
      '0.500" (1/2)',
      '0.750" (3/4)',
      '1.000" (1)',
      '1.500" (1-1/2)',
      '2.000" (2)',
      '3.000" (3)',
    ],
    relatedGrades: ["6061-T651", "2024-T351", "2124-T851"],
    description:
      "7075-T651 aluminum plate blanks are the premier choice for CNC machining of high-strength aerospace and defense components from thick stock. The T651 temper designation indicates the plate has been solution heat treated, stress relieved by controlled stretching (1-3% permanent set), and artificially aged. The stress relief step is critical for plate products because it minimizes internal residual stresses that would otherwise cause warping and distortion during machining.\n\nWith tensile strength of 83,000 psi and yield strength of 73,000 psi, 7075-T651 plate provides structural performance approaching that of many steels at 2.81 g/cm\u00B3 density. This makes it the material of choice for machined-from-solid aerospace parts such as wing ribs, fuselage frames, bulkheads, and landing gear components. The defense sector uses 7075 plate extensively for armored vehicle components, weapon system housings, and tactical equipment.\n\n7075-T651 plate machines exceptionally well on CNC mills. The combination of high hardness and the stress-relieved condition produces predictable chip formation, excellent surface finish, and dimensional stability through multi-setup machining operations. Cutting speeds of 500-1,000 SFM with carbide tooling and aggressive depths of cut are standard practice.\n\nOur 7075-T651 plate blanks are saw-cut from certified domestic mill plate conforming to AMS-QQ-A-250/12 and ASTM B209. Standard thicknesses range from 0.250 inches through 3.000 inches, with full material certifications and heat lot traceability available for every order.",
  },
  // --- Aluminum: 2024-T3 Sheet ---
  {
    material: "aluminum",
    grade: "2024-T3",
    form: "sheet",
    slug: "aluminum/sheet/2024-t3",
    displayName: "2024-T3 Aluminum Sheet Blanks",
    properties: {
      Alloy: "2024 (UNS A92024)",
      Form: "Sheet",
      "Temper/Condition": "T3 (Solution heat treated, cold worked, naturally aged)",
      Density: "0.100 lb/in\u00B3 (2.78 g/cm\u00B3)",
      "Tensile Strength": "70,000 psi (483 MPa)",
      "Yield Strength": "50,000 psi (345 MPa)",
      Hardness: "120 Brinell",
    },
    commonUses: [
      "Aircraft fuselage skins and panels",
      "Wing skins and structural shear webs",
      "Aerospace gussets and fittings",
      "Truck body and trailer panels",
      "Structural screw machine parts",
      "High-fatigue-life components",
    ],
    commonThicknesses: [
      '0.020"',
      '0.025"',
      '0.032"',
      '0.040"',
      '0.063"',
      '0.080"',
      '0.090"',
      '0.125"',
    ],
    relatedGrades: ["7075-T6", "6061-T6", "2024-T4"],
    description:
      "2024-T3 aluminum sheet blanks are the original high-strength aerospace aluminum, with a legacy stretching back to the 1930s when they became the skin material for the DC-3 and virtually every significant commercial and military aircraft that followed. The 2024 alloy is a copper-based system (3.8-4.9% copper, 1.2-1.8% magnesium, 0.3-0.9% manganese) that achieves high strength through natural aging after solution heat treatment and cold working.\n\nFatigue resistance is the property that sets 2024-T3 apart from other high-strength aluminum alloys. Under cyclic loading conditions typical of pressurized aircraft fuselages, 2024-T3 significantly outperforms 7075-T6 in crack initiation resistance and slow crack growth behavior. This damage-tolerant behavior is why 2024-T3 remains the standard fuselage skin material even as newer alloys have entered the market.\n\n2024-T3 is typically sold with an alclad coating \u2014 a thin layer of commercially pure aluminum metallurgically bonded to each surface that provides galvanic corrosion protection. Bare 2024-T3 has relatively poor corrosion resistance due to its high copper content. For applications where the alclad layer would be machined away, chemical conversion coating or anodizing is recommended.\n\nThe alloy is not recommended for fusion welding due to hot-cracking susceptibility and severe property degradation in the heat-affected zone. Riveting is the standard joining method for aircraft structures. Our 2024-T3 sheet blanks are available in both bare and alclad configurations, sheared from certified aerospace mill stock in thicknesses from 0.020 inches through 0.125 inches.",
  },
  // --- Aluminum: 6061-T651 Plate ---
  {
    material: "aluminum",
    grade: "6061-T651",
    form: "plate",
    slug: "aluminum/plate/6061-t6",
    displayName: "6061-T6 Aluminum Plate Blanks",
    properties: {
      Alloy: "6061 (UNS A96061)",
      Form: "Plate",
      "Temper/Condition": "T651 (Solution heat treated, stress relieved, artificially aged)",
      Density: "0.098 lb/in\u00B3 (2.70 g/cm\u00B3)",
      "Tensile Strength": "45,000 psi (310 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "95 Brinell",
    },
    commonUses: [
      "CNC machined fixtures and tooling plates",
      "Vacuum chamber components",
      "Base plates for automation equipment",
      "Mold plates for plastic injection",
      "Marine deck hardware and fittings",
      "Prototype structural components",
    ],
    commonThicknesses: [
      '0.250" (1/4)',
      '0.375" (3/8)',
      '0.500" (1/2)',
      '0.750" (3/4)',
      '1.000" (1)',
      '1.500" (1-1/2)',
      '2.000" (2)',
      '3.000" (3)',
    ],
    relatedGrades: ["7075-T651", "6061-T6 sheet", "MIC-6 cast plate"],
    description:
      "6061-T651 aluminum plate blanks are the workhorse material for CNC machining, tooling, and structural fabrication where thicknesses of 0.250 inches and above are required. The T651 temper indicates the plate has been solution heat treated, stress relieved by controlled stretching, and artificially aged \u2014 the stretching step reduces internal residual stresses that would otherwise cause warping when material is removed during machining.\n\n6061-T651 plate is the most popular aluminum alloy for general-purpose CNC machining, and for good reason. It machines cleanly at high speeds with excellent surface finish, accepts anodizing with consistent color and coating quality, and can be welded when needed using 4043 or 5356 filler wire. No other aluminum alloy matches this combination of machinability, finishability, weldability, and moderate strength at a reasonable price point.\n\nTooling plate is one of the highest-volume applications. Fixture plates, vacuum tables, jig bases, and modular fixturing systems are routinely machined from 6061-T651 plate because it offers sufficient rigidity and strength for workholding applications while being far easier to machine than steel alternatives.\n\nFor applications requiring superior flatness beyond standard mill plate tolerances, MIC-6 cast aluminum plate is an alternative worth considering, though it has lower mechanical properties than wrought 6061-T651. Our plate blanks are saw-cut from certified domestic mill plate conforming to ASTM B209. Standard thicknesses range from 0.250 inches through 3.000 inches.",
  },
  // --- Aluminum: 6061-T6 Bar ---
  {
    material: "aluminum",
    grade: "6061-T6511",
    form: "bar",
    slug: "aluminum/bar/6061-t6",
    displayName: "6061-T6 Aluminum Bar Stock",
    properties: {
      Alloy: "6061 (UNS A96061)",
      Form: "Bar (Round & Flat)",
      "Temper/Condition": "T6511 (Solution heat treated, stress relieved, artificially aged)",
      Density: "0.098 lb/in\u00B3 (2.70 g/cm\u00B3)",
      "Tensile Strength": "45,000 psi (310 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "95 Brinell",
    },
    commonUses: [
      "CNC turned shafts and pins",
      "Machined fittings and couplings",
      "Structural frame members",
      "Anodized architectural trim",
      "Hydraulic valve bodies",
      "Custom fasteners and standoffs",
    ],
    commonThicknesses: [
      '1/4" round bar',
      '3/8" round bar',
      '1/2" round bar',
      '3/4" round bar',
      '1" round bar',
      '1/4" x 1" flat bar',
      '1/2" x 2" flat bar',
      '3/4" x 1-1/2" flat bar',
    ],
    relatedGrades: ["7075-T6", "2024-T351", "6063-T5"],
    description:
      "6061-T6 aluminum bar stock is the most versatile aluminum bar product on the market, available in both round and flat configurations for lathe turning, CNC milling, and structural fabrication. The T6511 temper designation used for extruded bar indicates the material has been solution heat treated, stress relieved by controlled stretching, and artificially aged, providing the same 45,000 psi tensile strength and 95 Brinell hardness as 6061-T6 sheet and plate.\n\nRound bar is the starting stock for lathe-turned components \u2014 shafts, bushings, spacers, standoffs, pins, and custom fasteners. 6061-T6 round bar turns cleanly with good chip control and produces excellent surface finishes at cutting speeds of 500-1,500 SFM with carbide tooling. The alloy's free-cutting nature and dimensional consistency make it the preferred material for CNC production runs of turned aluminum parts.\n\nFlat bar serves as convenient stock for milling operations where the part cross-section approximates a rectangular profile. Starting with flat bar closer to the finished part dimensions reduces material waste and roughing time compared to machining from plate.\n\nBoth round and flat bar configurations weld reliably with standard TIG and MIG processes using 4043 or 5356 filler, and anodize with the same consistent results as 6061 sheet and plate. Our bar stock is cut to length from certified domestic mill stock meeting ASTM B221. Round bar is available from 1/4 inch through 6 inch diameter.",
  },
  // --- Aluminum: 3003-H14 Sheet ---
  {
    material: "aluminum",
    grade: "3003-H14",
    form: "sheet",
    slug: "aluminum/sheet/3003-h14",
    displayName: "3003-H14 Aluminum Sheet Blanks",
    properties: {
      Alloy: "3003 (UNS A93003)",
      Form: "Sheet",
      "Temper/Condition": "H14 (Strain-hardened to half-hard)",
      Density: "0.099 lb/in\u00B3 (2.73 g/cm\u00B3)",
      "Tensile Strength": "22,000 psi (152 MPa)",
      "Yield Strength": "21,000 psi (145 MPa)",
      Hardness: "40 Brinell",
    },
    commonUses: [
      "HVAC ductwork and plenums",
      "Cooking utensils and bakeware",
      "Chemical equipment and tanks",
      "Roofing, siding, and flashing",
      "Formed enclosures and covers",
      "Heat exchangers and fin stock",
    ],
    commonThicknesses: [
      '0.025"',
      '0.032"',
      '0.040"',
      '0.050"',
      '0.063"',
      '0.080"',
      '0.090"',
      '0.125"',
    ],
    relatedGrades: ["5052-H32", "1100-H14", "3003-H16"],
    description:
      "3003-H14 aluminum sheet blanks are the most widely used aluminum alloy for forming, drawing, and general sheet metal work where moderate strength and excellent workability are the primary requirements. The 3003 alloy is essentially commercially pure aluminum with a 1.0-1.5% manganese addition that increases strength by approximately 20% over 1100 series pure aluminum while maintaining nearly equivalent formability and corrosion resistance.\n\n3003-H14 is the standard material for HVAC ductwork fabrication, where it is roll-formed, seamed, and bent into rectangular and round duct sections. The alloy's low hardness and high ductility allow it to pass through roll-forming equipment without cracking, while the H14 temper provides sufficient rigidity to maintain duct shape.\n\nThe alloy's corrosion resistance and non-toxic nature make it approved for food-contact applications. Bakeware, cooking pots, storage containers, and food processing equipment are commonly fabricated from 3003 sheet. Its high thermal conductivity ensures even heat distribution in cookware applications.\n\n3003 is not a good candidate for CNC machining because its softness produces gummy, difficult-to-evacuate chips and poor surface finish. For machining-intensive parts, 6061-T6 is always the better choice. 3003-H14 sheet blanks are best suited for operations dominated by shearing, bending, punching, roll forming, and spinning. Our blanks are sheared from certified mill coil stock in thicknesses from 0.025 inches through 0.125 inches.",
  },
  // --- Titanium: Grade 2 CP Sheet ---
  {
    material: "titanium",
    grade: "Grade 2",
    form: "sheet",
    slug: "titanium/sheet/grade-2",
    displayName: "Grade 2 CP Titanium Sheet Blanks",
    properties: {
      Alloy: "Grade 2 CP Titanium (UNS R50400)",
      Form: "Sheet",
      "Temper/Condition": "Annealed",
      Density: "0.163 lb/in\u00B3 (4.51 g/cm\u00B3)",
      "Tensile Strength": "50,000 psi min (345 MPa)",
      "Yield Strength": "40,000 psi min (275 MPa)",
      Hardness: "200 Brinell (80 HRB)",
    },
    commonUses: [
      "Chemical processing heat exchangers",
      "Marine and desalination equipment",
      "Medical and dental implant components",
      "Exhaust systems and headers",
      "Jewelry and watch cases",
      "Architectural cladding and roofing",
    ],
    commonThicknesses: [
      '0.016"',
      '0.020"',
      '0.032"',
      '0.040"',
      '0.063"',
      '0.080"',
      '0.125"',
      '0.187"',
    ],
    relatedGrades: ["Grade 1 CP", "Grade 5 (Ti-6Al-4V)", "Grade 7 (Ti-Pd)"],
    description:
      "Grade 2 commercially pure titanium sheet blanks are the most widely used titanium product in the chemical processing, marine, and medical industries. Grade 2 is the workhorse of the four commercially pure titanium grades, offering the best balance between strength, formability, and corrosion resistance. With a minimum tensile strength of 50,000 psi and minimum yield strength of 40,000 psi in the annealed condition, Grade 2 CP titanium provides moderate structural capability at just 57% of the density of steel.\n\nCorrosion resistance is the primary reason engineers specify Grade 2 titanium over cheaper alternatives. The alloy forms a tenacious, self-healing titanium dioxide passive layer that resists attack from chloride solutions, seawater, wet chlorine gas, oxidizing acids, and many organic chemicals that rapidly degrade stainless steels. This makes Grade 2 sheet the standard construction material for heat exchangers, reaction vessels, piping, and valve trim in chlor-alkali plants and desalination facilities.\n\nGrade 2 titanium sheet offers good formability in the annealed condition, with 20% minimum elongation allowing brake forming, hydroforming, and moderate draw operations. Springback is more pronounced than with steel or aluminum, typically requiring 2-4 degrees of overbend compensation.\n\nThe alloy is fully biocompatible per ASTM F67, making it the standard material for medical device housings, dental implant abutments, and surgical instrument components. Grade 2 titanium welds cleanly with TIG using argon shielding and matching Grade 2 filler wire. Our sheet blanks are sheared from certified ASTM B265 mill stock in thicknesses from 0.016 inches through 0.187 inches.",
  },
  // --- Titanium: Grade 5 Ti-6Al-4V Plate ---
  {
    material: "titanium",
    grade: "Grade 5 (Ti-6Al-4V)",
    form: "plate",
    slug: "titanium/plate/grade-5",
    displayName: "Grade 5 Ti-6Al-4V Titanium Plate Blanks",
    properties: {
      Alloy: "Grade 5 Ti-6Al-4V (UNS R56400)",
      Form: "Plate",
      "Temper/Condition": "Annealed (Mill Annealed)",
      Density: "0.160 lb/in\u00B3 (4.43 g/cm\u00B3)",
      "Tensile Strength": "130,000 psi min (895 MPa)",
      "Yield Strength": "120,000 psi min (828 MPa)",
      Hardness: "334 Brinell (36 HRC)",
    },
    commonUses: [
      "Aerospace structural bulkheads and frames",
      "Jet engine compressor blades and discs",
      "Surgical implant plates and spinal hardware",
      "Marine propeller shafts and fittings",
      "High-performance racing components",
      "Military armor and ballistic plates",
    ],
    commonThicknesses: [
      '0.250" (1/4)',
      '0.375" (3/8)',
      '0.500" (1/2)',
      '0.750" (3/4)',
      '1.000" (1)',
      '1.500" (1-1/2)',
      '2.000" (2)',
    ],
    relatedGrades: ["Grade 23 (Ti-6Al-4V ELI)", "Grade 2 CP", "Ti-6Al-2Sn-4Zr-2Mo"],
    description:
      "Grade 5 Ti-6Al-4V titanium plate blanks represent the highest-performance structural metal commercially available for CNC machining of aerospace, medical, and defense components. Ti-6Al-4V is an alpha-beta alloy containing 6% aluminum and 4% vanadium that accounts for more than 50% of all titanium used worldwide. In the mill-annealed condition, the alloy delivers a minimum tensile strength of 130,000 psi and yield strength of 120,000 psi at a density of just 0.160 lb/in\u00B3 \u2014 providing a specific strength that exceeds every commonly used steel and aluminum alloy.\n\nAerospace applications consume the majority of Ti-6Al-4V plate production. Structural bulkheads, wing carry-through structures, engine mount fittings, and landing gear components are CNC machined from plate stock on high-rigidity five-axis machines. The alloy's excellent fatigue strength, which approaches 50% of ultimate tensile strength at 10 million cycles, makes it the material of choice for dynamically loaded airframe components.\n\nMachining Ti-6Al-4V plate requires careful technique but produces excellent results with proper setup. Sharp carbide inserts with positive rake geometry, cutting speeds of 100-200 SFM, aggressive chip loads, high-pressure through-spindle coolant, and climb milling are the keys to productive titanium machining.\n\nTi-6Al-4V plate can be solution treated and aged (STA) to increase tensile strength to approximately 170,000 psi for applications requiring maximum mechanical performance. Our plate blanks are saw-cut from certified ASTM B265 and AMS 4911 mill plate in thicknesses from 0.250 inches through 2.000 inches, with full chemical and mechanical test reports included.",
  },
  // --- Titanium: Grade 5 Ti-6Al-4V Bar ---
  {
    material: "titanium",
    grade: "Grade 5 (Ti-6Al-4V)",
    form: "bar",
    slug: "titanium/bar/grade-5",
    displayName: "Grade 5 Ti-6Al-4V Titanium Bar Stock",
    properties: {
      Alloy: "Grade 5 Ti-6Al-4V (UNS R56400)",
      Form: "Bar (Round)",
      "Temper/Condition": "Annealed (Mill Annealed)",
      Density: "0.160 lb/in\u00B3 (4.43 g/cm\u00B3)",
      "Tensile Strength": "130,000 psi min (895 MPa)",
      "Yield Strength": "120,000 psi min (828 MPa)",
      Hardness: "334 Brinell (36 HRC)",
    },
    commonUses: [
      "Aerospace fasteners and bolts",
      "Orthopedic bone screws and rods",
      "CNC turned valve stems and fittings",
      "Racing connecting rods and drivetrain",
      "Marine propeller shafts",
      "Downhole oil and gas components",
    ],
    commonThicknesses: [
      '1/4" round bar',
      '3/8" round bar',
      '1/2" round bar',
      '3/4" round bar',
      '1" round bar',
      '1-1/2" round bar',
      '2" round bar',
      '3" round bar',
    ],
    relatedGrades: ["Grade 23 (Ti-6Al-4V ELI)", "Grade 2 CP bar", "Ti-6Al-2Sn-4Zr-6Mo"],
    description:
      "Grade 5 Ti-6Al-4V titanium bar stock is the premium material for CNC turned and machined components requiring the highest strength-to-weight ratio available in a metallic material. Ti-6Al-4V round bar delivers the same exceptional mechanical properties as the plate product \u2014 130,000 psi minimum tensile strength and 120,000 psi minimum yield strength \u2014 in a form factor optimized for lathe turning, Swiss-style machining, and CNC production of round cross-section parts.\n\nAerospace fasteners represent one of the highest-volume applications for Ti-6Al-4V bar. Bolts, screws, nuts, and studs machined from Grade 5 bar stock replace steel fasteners at approximately 43% weight savings in airframe and engine applications. The alloy's excellent fatigue strength ensures these fasteners withstand millions of load cycles in vibration-intensive environments.\n\nMedical device manufacturing is the second major consumer of Grade 5 titanium bar. Orthopedic bone screws, spinal fusion rods, dental implant bodies, and surgical drill guides are CNC turned from bar stock meeting ASTM F136 or ASTM B348. The alloy's proven biocompatibility, osseointegration capability, and MRI compatibility make it the dominant material for load-bearing implant applications.\n\nTurning Ti-6Al-4V bar on a CNC lathe requires sharp coated carbide inserts (PVD TiAlN recommended), cutting speeds of 120-180 SFM, positive feed rates of 0.004-0.010 inches per revolution, and flood coolant. Our Ti-6Al-4V round bar is cut to length from certified ASTM B348 and AMS 4928 mill bar in diameters from 1/4 inch through 3 inches.",
  },
  // --- Stainless Steel: 316 Sheet ---
  {
    material: "stainless-steel",
    grade: "316",
    form: "sheet",
    slug: "stainless-steel/sheet/316",
    displayName: "316 Stainless Steel Sheet Blanks",
    properties: {
      Alloy: "AISI 316 (UNS S31600)",
      Form: "Sheet",
      "Temper/Condition": "Annealed (2B Mill Finish)",
      Density: "0.289 lb/in\u00B3 (8.00 g/cm\u00B3)",
      "Tensile Strength": "75,000 psi (515 MPa)",
      "Yield Strength": "30,000 psi (205 MPa)",
      Hardness: "149 Brinell (79 HRB)",
    },
    commonUses: [
      "Marine hardware and boat fittings",
      "Pharmaceutical processing equipment",
      "Chemical storage tanks and piping",
      "Medical device housings and trays",
      "Food processing equipment for chlorinated environments",
      "Coastal architectural trim and fasteners",
    ],
    commonThicknesses: [
      '0.030" (22 gauge)',
      '0.048" (18 gauge)',
      '0.060" (16 gauge)',
      '0.075" (14 gauge)',
      '0.105" (12 gauge)',
      '0.120" (11 gauge)',
      '0.187" (3/16)',
      '0.250" (1/4)',
    ],
    relatedGrades: ["304", "316L", "317L", "904L"],
    description:
      "316 stainless steel sheet blanks are the premium austenitic stainless grade for applications demanding superior corrosion resistance, particularly in chloride-bearing environments where standard 304 falls short. The critical difference is the addition of 2-3% molybdenum to the 16-18% chromium and 10-14% nickel base composition, which dramatically improves resistance to pitting and crevice corrosion from chlorides, saltwater, and aggressive cleaning chemicals.\n\nMarine environments are where 316 earns its reputation. Boat hardware, deck fittings, railing components, and underwater fasteners made from 316 sheet resist the pitting corrosion that degrades 304 in continuous saltwater exposure. This same chloride resistance makes 316 the standard grade for pharmaceutical cleanrooms where chlorinated sanitizers are used daily.\n\nThe mechanical properties of 316 sheet closely mirror 304, with a minimum tensile strength of 75,000 psi and 30,000 psi yield strength in the annealed condition. Elongation of 40% minimum ensures excellent formability for brake bending, stamping, and drawing operations.\n\nWelding 316 sheet follows the same practices as 304, using TIG or MIG with 316L filler wire to maintain corrosion resistance in the weld zone. Post-weld passivation with citric or nitric acid restores the full corrosion resistance of the heat-affected zone. Our 316 stainless sheet blanks are sheared from certified 2B mill finish coil stock in gauges from 22 gauge through 1/4 inch.",
  },
  // --- Stainless Steel: 303 Bar ---
  {
    material: "stainless-steel",
    grade: "303",
    form: "bar",
    slug: "stainless-steel/bar/303",
    displayName: "303 Free-Machining Stainless Bar Blanks",
    properties: {
      Alloy: "AISI 303 (UNS S30300)",
      Form: "Bar",
      "Temper/Condition": "Annealed, Cold Finished",
      Density: "0.289 lb/in\u00B3 (8.03 g/cm\u00B3)",
      "Tensile Strength": "90,000 psi (620 MPa)",
      "Yield Strength": "35,000 psi (241 MPa)",
      Hardness: "228 Brinell (96 HRB)",
    },
    commonUses: [
      "Screw machine products and fittings",
      "Shafts, valve stems, and actuator components",
      "Nuts, bolts, and custom threaded fasteners",
      "Gear blanks and bearing spacers",
      "Instrument parts and sensor housings",
      "Aircraft fittings and avionics hardware",
    ],
    commonThicknesses: [
      '1/4" round bar',
      '3/8" round bar',
      '1/2" round bar',
      '5/8" round bar',
      '3/4" round bar',
      '1" round bar',
      '1-1/4" round bar',
      '1-1/2" round bar',
    ],
    relatedGrades: ["304", "303Se", "416"],
    description:
      "303 stainless steel bar blanks are the free-machining variant of the austenitic 300-series family, engineered specifically for high-speed CNC turning, screw machine operations, and any application where machinability is the primary material selection criterion. The addition of sulfur (0.15% minimum) creates manganese sulfide inclusions that act as chip breakers during cutting, dramatically improving tool life and enabling faster feed rates compared to 304 or 316.\n\nThe machinability advantage of 303 over standard austenitic grades is substantial. Where 304 rates approximately 45% on the B1112 free-machining steel scale, 303 achieves roughly 78%, representing a significant improvement in production throughput and tooling cost. Chips break cleanly and evacuate efficiently from automatic screw machines and CNC lathes.\n\nThe corrosion resistance of 303 is slightly lower than 304 due to the sulfide inclusions, which can act as initiation sites for pitting in aggressive environments. For most atmospheric, mild chemical, and indoor applications, the difference is negligible. The sulfur content also makes 303 unsuitable for welding, as the sulfide inclusions cause hot cracking in the weld zone.\n\n303 bar stock is available in round, hexagonal, and square cross-sections to accommodate different chucking and machining requirements. Our 303 stainless bar blanks are cold-finished to ensure excellent surface quality and dimensional accuracy, cut to length from certified domestic mill stock in diameters from 1/4 inch through 1-1/2 inches.",
  },
  // --- Stainless Steel: 410 Plate ---
  {
    material: "stainless-steel",
    grade: "410",
    form: "plate",
    slug: "stainless-steel/plate/410",
    displayName: "410 Stainless Steel Plate Blanks",
    properties: {
      Alloy: "AISI 410 (UNS S41000)",
      Form: "Plate",
      "Temper/Condition": "Annealed",
      Density: "0.280 lb/in\u00B3 (7.75 g/cm\u00B3)",
      "Tensile Strength": "70,000 psi (485 MPa) annealed; up to 180,000 psi hardened",
      "Yield Strength": "45,000 psi (310 MPa) annealed; up to 140,000 psi hardened",
      Hardness: "155 Brinell annealed; up to 41 HRC hardened",
    },
    commonUses: [
      "Valve and pump components",
      "Cutlery and kitchen knife blades",
      "Turbine blades and steam equipment",
      "Petroleum refining equipment",
      "Mine ladder rungs and wear plates",
      "Fasteners requiring moderate corrosion resistance",
    ],
    commonThicknesses: [
      '0.250" (1/4)',
      '0.375" (3/8)',
      '0.500" (1/2)',
      '0.750" (3/4)',
      '1.000" (1)',
      '1.250" (1-1/4)',
      '1.500" (1-1/2)',
      '2.000" (2)',
    ],
    relatedGrades: ["420", "440C", "416"],
    description:
      "410 stainless steel plate blanks are the most widely used martensitic stainless grade, offering a unique combination of moderate corrosion resistance with the ability to be heat treated to high hardness levels that austenitic grades like 304 and 316 cannot achieve. With 11.5-13.5% chromium and up to 0.15% carbon, 410 occupies the critical position where stainless corrosion resistance meets hardenability.\n\nIn the annealed condition, 410 plate machines readily and can be formed, drilled, and fabricated using standard shop practices. After fabrication, the material can be hardened by austenitizing at 1,800\u00B0F followed by oil or air quenching, then tempered between 400-1,400\u00B0F to achieve the desired balance of hardness and toughness. Typical heat-treated hardness ranges from 35-41 HRC.\n\nThe corrosion resistance of 410 exceeds that of carbon and alloy steels by a wide margin, resisting atmospheric corrosion, mild chemicals, fresh water, and steam. However, it does not approach the performance of austenitic grades in chloride or acidic environments. The best corrosion resistance is achieved in the hardened and tempered condition with a polished or passivated surface finish.\n\nWelding 410 plate requires preheat of 400-600\u00B0F and controlled interpass temperature to prevent cold cracking in the heat-affected zone. Post-weld heat treatment is strongly recommended. Our 410 stainless plate blanks ship in the annealed condition for maximum machinability and formability, cut from certified mill plate in thicknesses from 1/4 inch through 2 inches.",
  },
  // --- Stainless Steel: 17-4 PH Bar ---
  {
    material: "stainless-steel",
    grade: "17-4 PH",
    form: "bar",
    slug: "stainless-steel/bar/17-4-ph",
    displayName: "17-4 PH Stainless Steel Bar Blanks",
    properties: {
      Alloy: "17-4 PH (UNS S17400, Type 630)",
      Form: "Bar",
      "Temper/Condition": "Condition A (Solution Annealed)",
      Density: "0.282 lb/in\u00B3 (7.81 g/cm\u00B3)",
      "Tensile Strength": "190,000 psi (1,310 MPa) at H900",
      "Yield Strength": "170,000 psi (1,170 MPa) at H900",
      Hardness: "44 HRC at H900; 33 HRC at H1150",
    },
    commonUses: [
      "Aerospace structural components and landing gear fittings",
      "Oil and gas valve stems and downhole tools",
      "Medical instrument shafts and surgical tools",
      "High-strength fasteners and studs",
      "Nuclear reactor components",
      "Food processing shafts and spindles",
    ],
    commonThicknesses: [
      '1/2" round bar',
      '3/4" round bar',
      '1" round bar',
      '1-1/4" round bar',
      '1-1/2" round bar',
      '2" round bar',
      '2-1/2" round bar',
      '3" round bar',
    ],
    relatedGrades: ["15-5 PH", "13-8 Mo", "455 Custom"],
    description:
      "17-4 PH stainless steel bar blanks deliver aerospace-grade strength with stainless corrosion resistance, making them one of the most specified precipitation-hardened alloys in demanding industrial applications. The designation reflects the nominal composition of 17% chromium and 4% nickel, with critical additions of 3-5% copper and 0.15-0.45% columbium that enable the precipitation hardening mechanism. This alloy achieves tensile strengths up to 190,000 psi while maintaining corrosion resistance comparable to 304 stainless.\n\nThe precipitation hardening process is what sets 17-4 PH apart from conventional stainless steels. The material ships in Condition A (solution annealed at 1,900\u00B0F), which provides moderate hardness of approximately 36 HRC and is the easiest condition to machine. After machining to near-net shape, parts are aged at temperatures between 900 and 1,150\u00B0F for one to four hours. The H900 condition produces maximum strength at 44 HRC, while H1150 offers the best combination of toughness and corrosion resistance at 33 HRC.\n\nThe low aging temperatures are a significant practical advantage. Parts can be hardened in a simple air furnace without protective atmosphere, and the dimensional change during aging is typically less than 0.0005 inches per inch, allowing tight-tolerance parts to be finish-machined before hardening.\n\nMachinability in Condition A is good, comparable to 304 stainless, using carbide tooling with positive rake geometry and adequate coolant. Our 17-4 PH bar blanks are supplied in Condition A, saw-cut from certified AMS 5643 mill stock in diameters from 1/2 inch through 3 inches.",
  },
  // --- Copper: C101 OFHC Sheet ---
  {
    material: "copper",
    grade: "C101",
    form: "sheet",
    slug: "copper/sheet/c101",
    displayName: "C101 OFHC Copper Sheet Blanks",
    properties: {
      Alloy: "C101 OFE/OFHC (UNS C10100)",
      Form: "Sheet",
      "Temper/Condition": "H02 (Half Hard)",
      Density: "0.323 lb/in\u00B3 (8.94 g/cm\u00B3)",
      "Tensile Strength": "38,000 psi (262 MPa)",
      "Yield Strength": "30,000 psi (207 MPa)",
      Hardness: "60 HRF",
    },
    commonUses: [
      "Vacuum tube and electron beam components",
      "High-purity semiconductor busbars",
      "Superconductor stabilization strips",
      "Waveguide and RF cavity linings",
      "Cryogenic heat exchangers",
      "High-frequency electrical connectors",
    ],
    commonThicknesses: [
      '0.020"',
      '0.032" (20 gauge)',
      '0.040" (18 gauge)',
      '0.063" (16 gauge)',
      '0.093"',
      '0.125" (1/8)',
      '0.187" (3/16)',
      '0.250" (1/4)',
    ],
    relatedGrades: ["C110", "C102", "C145"],
    description:
      "C101 OFE (Oxygen-Free Electronic) copper sheet blanks represent the highest commercially available purity grade of copper, refined to 99.99% minimum copper content with oxygen levels below 0.0005%. This extreme purity eliminates the risk of hydrogen embrittlement during brazing and high-temperature processing, and minimizes outgassing in vacuum environments, making C101 the mandatory material for particle accelerator components, electron tubes, vacuum feedthroughs, and semiconductor manufacturing equipment.\n\nThe electrical conductivity of 101% IACS is nominally identical to C110 ETP copper, but the absence of cuprous oxide inclusions gives C101 superior performance in several critical areas: more consistent conductivity at cryogenic temperatures, lower outgassing rates under vacuum, and freedom from the embrittlement that occurs when ETP copper is heated above 750\u00B0F in hydrogen-containing atmospheres.\n\nVacuum and high-energy physics applications drive most C101 demand. Particle accelerator cavities, RF waveguide components, and electron gun assemblies require copper that will not release gas molecules under hard vacuum. The semiconductor industry specifies C101 for sputtering targets and gas delivery system components where trace oxygen would contaminate processes.\n\nThe mechanical properties of C101 sheet are essentially identical to C110 at equivalent tempers. Half-hard temper provides a practical balance of strength and formability. C101 solders, brazes, and welds using the same techniques as other pure coppers, with the critical advantage that brazing in hydrogen atmospheres will not cause embrittlement. Our C101 sheet blanks ship with protective interleaving from certified oxygen-free mill stock in thicknesses from 0.020 inches through 1/4 inch.",
  },
  // --- Copper: C122 DHP Sheet ---
  {
    material: "copper",
    grade: "C122",
    form: "sheet",
    slug: "copper/sheet/c122",
    displayName: "C122 DHP Copper Sheet Blanks",
    properties: {
      Alloy: "C122 DHP (UNS C12200)",
      Form: "Sheet",
      "Temper/Condition": "H02 (Half Hard)",
      Density: "0.323 lb/in\u00B3 (8.94 g/cm\u00B3)",
      "Tensile Strength": "38,000 psi (262 MPa)",
      "Yield Strength": "30,000 psi (207 MPa)",
      Hardness: "60 HRF",
    },
    commonUses: [
      "Plumbing tube and fittings fabrication",
      "HVAC heat exchanger fins and headers",
      "Solar thermal collector panels",
      "Brazed refrigeration assemblies",
      "Roofing, flashing, and architectural cladding",
      "Distillation column components",
    ],
    commonThicknesses: [
      '0.021" (24 gauge)',
      '0.032" (20 gauge)',
      '0.040" (18 gauge)',
      '0.063" (16 gauge)',
      '0.093"',
      '0.125" (1/8)',
      '0.187" (3/16)',
      '0.250" (1/4)',
    ],
    relatedGrades: ["C110", "C101", "C120"],
    description:
      "C122 DHP (Deoxidized High Phosphorus) copper sheet blanks are the standard copper grade for plumbing, HVAC, and any application involving brazing or soldering in assembly. The defining characteristic of C122 is its phosphorus content of 0.015-0.040%, which serves as a deoxidizer during melting and remains in the finished product as a residual element that dramatically improves brazeability. This phosphorus content allows C122 to be brazed with copper-phosphorus (BCuP) filler alloys without the need for flux.\n\nThe deoxidized composition means C122 is free of the cuprous oxide network present in C110 ETP copper. When ETP copper is heated above approximately 750\u00B0F in a hydrogen-containing atmosphere, hydrogen diffuses into the copper and reacts with the internal oxide particles, causing intergranular cracking known as hydrogen embrittlement. C122 eliminates this failure mode entirely, making it the safe choice for any application where the copper will be exposed to high temperatures during brazing, welding, or service.\n\nThe trade-off for phosphorus deoxidation is a reduction in electrical conductivity. C122 achieves approximately 85% IACS compared to the 101% IACS of C110 and C101. For electrical busbar and high-conductivity applications, C110 is the better choice. For plumbing, HVAC, architectural, and general fabrication applications where conductivity is not critical, C122 provides superior brazeability and processing reliability.\n\nOur C122 DHP sheet blanks are sheared from certified mill stock in thicknesses from 24 gauge through 1/4 inch.",
  },
  // --- Brass: C360 Free-Machining Bar ---
  {
    material: "brass",
    grade: "C360",
    form: "bar",
    slug: "brass/bar/c360",
    displayName: "C360 Free-Machining Brass Bar Blanks",
    properties: {
      Alloy: "C360 (UNS C36000)",
      Form: "Bar",
      "Temper/Condition": "Half Hard (H02)",
      Density: "0.307 lb/in\u00B3 (8.50 g/cm\u00B3)",
      "Tensile Strength": "58,000 psi (400 MPa)",
      "Yield Strength": "25,000 psi (172 MPa)",
      Hardness: "78 HRB (140 Brinell)",
    },
    commonUses: [
      "Screw machine products and automatic lathe parts",
      "Valve bodies, stems, and seats",
      "Plumbing fittings and adapters",
      "Gear blanks and clock components",
      "Electrical connectors and terminal blocks",
      "Pneumatic and hydraulic fittings",
    ],
    commonThicknesses: [
      '1/4" round bar',
      '3/8" round bar',
      '1/2" round bar',
      '5/8" round bar',
      '3/4" round bar',
      '1" round bar',
      '1-1/4" hex bar',
      '1-1/2" round bar',
    ],
    relatedGrades: ["C260", "C353", "C385"],
    description:
      "C360 free-machining brass bar blanks are the benchmark material against which all other copper alloy machinability ratings are measured, achieving the reference rating of 100 on the CDA machinability scale. The alloy composition of approximately 61.5% copper, 35.5% zinc, and 3% lead produces a microstructure where finely dispersed lead particles act as internal lubricants and chip breakers during cutting operations.\n\nThe machinability advantage of C360 is dramatic and directly translates to lower part costs. Cutting speeds of 300-400 surface feet per minute are routine with high-speed steel tooling, and carbide tooling pushes speeds even higher. The lead particles cause chips to break into small, easily evacuated fragments rather than the long, stringy chips produced by unleaded brass alloys. This clean chip formation allows unattended operation of automatic screw machines and Swiss-type lathes.\n\nThe 61.5/35.5 copper-zinc ratio places C360 in the alpha-beta brass range, giving it higher strength than the alpha-phase cartridge brass alloys while maintaining adequate corrosion resistance for most indoor and mild outdoor environments. The alloy resists dezincification better than higher-zinc brasses but is not recommended for continuous seawater immersion.\n\nC360 cannot be hardened by heat treatment; its mechanical properties are controlled through cold working during the drawing process. The alloy solders and brazes readily but is generally not welded due to the lead content. Our C360 brass bar blanks are available in round, hex, and square cross-sections, cold-drawn from certified domestic mill stock in sizes from 1/4 inch through 1-1/2 inches.",
  },
  // --- Brass: C464 Naval Brass Bar ---
  {
    material: "brass",
    grade: "C464",
    form: "bar",
    slug: "brass/bar/c464",
    displayName: "C464 Naval Brass Bar Blanks",
    properties: {
      Alloy: "C464 (UNS C46400)",
      Form: "Bar",
      "Temper/Condition": "Half Hard (H02)",
      Density: "0.304 lb/in\u00B3 (8.41 g/cm\u00B3)",
      "Tensile Strength": "75,000 psi (517 MPa)",
      "Yield Strength": "40,000 psi (276 MPa)",
      Hardness: "85 HRB (150 Brinell)",
    },
    commonUses: [
      "Marine propeller shafts and hardware",
      "Seawater valve stems and pump components",
      "Structural bolts and nuts for marine service",
      "Turnbuckles and rigging fittings",
      "Condenser tube sheets and baffle plates",
      "Non-sparking tools for hazardous environments",
    ],
    commonThicknesses: [
      '3/8" round bar',
      '1/2" round bar',
      '5/8" round bar',
      '3/4" round bar',
      '1" round bar',
      '1-1/4" round bar',
      '1-1/2" round bar',
      '2" round bar',
    ],
    relatedGrades: ["C443", "C360", "C655"],
    description:
      "C464 naval brass bar blanks are the definitive copper-zinc alloy for marine and seawater service, engineered to resist the dezincification corrosion that degrades standard brass alloys in saltwater environments. The composition of approximately 60% copper, 39.25% zinc, and 0.75% tin creates a microstructure that maintains its integrity in continuous seawater exposure, where ordinary yellow brass would suffer selective leaching of zinc.\n\nThe tin addition is the critical difference between naval brass and standard Muntz metal. Even at less than 1%, tin fundamentally changes the alloy's corrosion behavior by stabilizing the beta phase against dezincification. This protection mechanism has been proven over more than a century of service in naval hardware, with C464 remaining the standard material for propeller shafts, through-hull fittings, valve stems, and structural fasteners on commercial and military vessels.\n\nMechanical properties of C464 exceed those of most other brass alloys. With tensile strength of 75,000 psi in the half-hard condition and good fatigue resistance, naval brass provides the structural capability needed for propeller shafts, rigging hardware, and fasteners subject to cyclic loading. The alloy also exhibits excellent hot forgeability for complex shapes.\n\nMachinability of C464 rates approximately 30 on the CDA scale (where C360 is 100), making it significantly more difficult to machine than leaded brass alloys. Sharp tooling, positive rake angles, and adequate coolant are required. The absence of lead also makes C464 compliant with lead-free requirements for potable water components under NSF/ANSI 61. Our C464 naval brass bar blanks are saw-cut from certified mill stock in diameters from 3/8 inch through 2 inches.",
  },
]

export function getMaterialPage(
  material: string,
  form: string,
  grade: string
): MaterialPage | undefined {
  return materialPages.find(
    (p) => p.slug === `${material}/${form}/${grade}`
  )
}

export function getMaterialPagesByMaterial(
  materialSlug: string
): MaterialPage[] {
  return materialPages.filter((p) => p.material === materialSlug)
}

export function getRelatedPageSlug(
  gradeName: string,
  currentMaterial: string
): string | undefined {
  const page = materialPages.find(
    (p) =>
      p.grade.toLowerCase() === gradeName.toLowerCase() ||
      p.grade.toLowerCase().includes(gradeName.toLowerCase())
  )
  return page?.slug
}
